#! /bin/sh


bspc monitor -d I II III IV V VI VII VIII 

bspc config border_width        3
bspc config window_gap          8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &

###############
## autostart ##
###############


## reload compton
pkill compton
compton -b &

# volume icon
pkill volumeicon
volumeicon &

# keybind daemon
pkill sxhkd
sxhkd &

## music is my only friend
pkill mpd
mpd &

## reload the xsettingsd, a minimal x settings daemon
#pkill xsettingsd
#xsettingsd &

## set the wallpaper - aqui é o caminho de seu wallpaper
feh --bg-fill Imagens/wallpaper/wallpaper67.png &
wal -i Imagens/wallpaper/wallpaper67.png &

## load dunst
pkill dunst
dunst &

$HOME/.config/polybar/launch.sh &


